import { notificationProvider, paymentProvider, repositories } from '../adapters/local';
import type { Deal, Equipment, ID, Installation, Invoice, Lead, Task, User, Visit, Warranty } from '../domain/types';
import { createId, nowIso } from '../utils';
import { auditService, eventService } from './eventAudit';

const managerId = () => repositories.rules.list('ws_kron') && 'u2';
const eventTitle = (type:string) => type.split('_').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
function clientForLead(lead: Lead): ID { return lead.clientId ?? 'c1'; }
function record(workspaceId:string, actor:User, action:string, entityType:string, entityId:string, before:unknown, after:unknown) { auditService.record({workspaceId,actorUserId:actor.id,action,entityType,entityId,before,after}); }
function emit(workspaceId:string, actor:User, type:string, entityType:string, entityId:string, payload:Record<string,string|number|boolean|undefined>={}) { return eventService.createEvent({workspaceId,type,title:eventTitle(type),entityType,entityId,actorUserId:actor.id,payload}); }

export class LeadService {
  createLead(workspaceId:string, actor:User, payload: Partial<Lead>) { const lead: Lead={id:createId('lead'),workspaceId,name:payload.name??'New lead',source:payload.source??'website',status:'new',priority:payload.priority??'medium',assignedUserId:payload.assignedUserId??actor.id,district:payload.district??'Kyiv',createdAt:nowIso(),clientId:payload.clientId}; repositories.leads.create(lead); record(workspaceId,actor,'lead.create','lead',lead.id,undefined,lead); return {entity:lead,event:emit(workspaceId,actor,'lead_created','lead',lead.id,{district:lead.district,priority:lead.priority})}; }
  qualifyLead(workspaceId:string, actor:User, id:ID) { const before={...repositories.leads.get(id)}; const lead=repositories.leads.update(id,{status:'qualified'}); if(!lead) throw new Error('Lead not found'); record(workspaceId,actor,'lead.qualify','lead',id,before,lead); return {entity:lead,event:emit(workspaceId,actor,'lead_qualified','lead',id,{district:lead.district,priority:lead.priority})}; }
  assignLead(workspaceId:string, actor:User, id:ID, assignedUserId:ID) { const before={...repositories.leads.get(id)}; const lead=repositories.leads.update(id,{assignedUserId}); if(!lead) throw new Error('Lead not found'); record(workspaceId,actor,'lead.assign','lead',id,before,lead); return {entity:lead,event:emit(workspaceId,actor,'lead_assigned','lead',id,{assignedUserId})}; }
}
export class DealService {
  createDealFromLead(workspaceId:string, actor:User, leadId:ID) { const lead=repositories.leads.get(leadId); if(!lead) throw new Error('Lead not found'); const deal:Deal={id:createId('deal'),workspaceId,clientId:clientForLead(lead),title:`Deal for ${lead.name}`,stage:'new',value:25000,assignedUserId:lead.assignedUserId}; repositories.deals.create(deal); repositories.leads.update(leadId,{status:'qualified'}); record(workspaceId,actor,'deal.create_from_lead','deal',deal.id,undefined,deal); return {entity:deal,event:emit(workspaceId,actor,'deal_created','deal',deal.id,{leadId})}; }
  updateDealStage(workspaceId:string, actor:User, id:ID, stage:Deal['stage']) { const before={...repositories.deals.get(id)}; const deal=repositories.deals.update(id,{stage}); if(!deal) throw new Error('Deal not found'); record(workspaceId,actor,`deal.${stage}`,'deal',id,before,deal); return {entity:deal,event:emit(workspaceId,actor,stage==='won'?'deal_won':stage==='lost'?'deal_lost':'deal_stage_updated','deal',id,{stage,value:deal.value,clientId:deal.clientId,invoiceId:deal.invoiceId})}; }
  markDealWon(w:string,a:User,id:ID){return this.updateDealStage(w,a,id,'won')} markDealLost(w:string,a:User,id:ID){return this.updateDealStage(w,a,id,'lost')}
}
export class TaskService { createTask(workspaceId:string, actor:User, payload: Partial<Task>) { const task:Task={id:createId('task'),workspaceId,title:payload.title??'Follow up',status:'open',priority:payload.priority??'medium',assigneeId:payload.assigneeId??actor.id,dueAt:payload.dueAt??nowIso(),relatedEntityType:payload.relatedEntityType,relatedEntityId:payload.relatedEntityId}; repositories.tasks.create(task); record(workspaceId,actor,'task.create','task',task.id,undefined,task); return {entity:task,event:emit(workspaceId,actor,'task_created','task',task.id,{relatedEntityId:task.relatedEntityId})}; } completeTask(workspaceId:string, actor:User, id:ID){const before={...repositories.tasks.get(id)}; const task=repositories.tasks.update(id,{status:'done'}); if(!task) throw new Error('Task not found'); record(workspaceId,actor,'task.complete','task',id,before,task); return {entity:task,event:emit(workspaceId,actor,'task_completed','task',id,{})};}}
export class InvoiceService { markInvoicePaid(workspaceId:string, actor:User, id:ID){const before={...repositories.invoices.get(id)}; const invoice=repositories.invoices.get(id); if(!invoice) throw new Error('Invoice not found'); const payment=paymentProvider.pay(invoice); const paid=repositories.invoices.update(id,{status:'paid'}); record(workspaceId,actor,'invoice.mark_paid','invoice',id,before,paid); notificationProvider.send({workspaceId,userId:actor.id,title:'Invoice paid',body:`${id} paid via ${payment.providerRef}`}); return {entity:paid as Invoice,event:emit(workspaceId,actor,'invoice_paid','invoice',id,{amount:invoice.total})};}}
export class ScheduleService { completeVisit(workspaceId:string, actor:User, id:ID){const before={...repositories.visits.get(id)}; const visit=repositories.visits.update(id,{status:'completed'}); if(!visit) throw new Error('Visit not found'); record(workspaceId,actor,'visit.complete','visit',id,before,visit); return {entity:visit,event:emit(workspaceId,actor,'visit_completed','visit',id,{type:visit.type,relatedEntityId:visit.relatedEntityId})};} scheduleVisit(workspaceId:string, actor:User, payload:Partial<Visit>){const visit:Visit={id:createId('visit'),workspaceId,title:payload.title??'Scheduled visit',type:payload.type??'survey',status:'planned',startsAt:payload.startsAt??nowIso(),endsAt:payload.endsAt??nowIso(),district:payload.district??'Kyiv',priority:payload.priority??'medium',skills:payload.skills??[],assignedUserId:payload.assignedUserId,assignedTeamId:payload.assignedTeamId,objectId:payload.objectId,relatedEntityType:payload.relatedEntityType,relatedEntityId:payload.relatedEntityId}; repositories.visits.create(visit); record(workspaceId,actor,'visit.schedule','visit',visit.id,undefined,visit); return {entity:visit,event:emit(workspaceId,actor,visit.type==='installation'?'installation_scheduled':'service_scheduled','visit',visit.id,{})};}}
export class HvacService { createInstallationFromDeal(workspaceId:string, actor:User, dealId:ID){const deal=repositories.deals.get(dealId); if(!deal) throw new Error('Deal not found'); const eq:Equipment={id:createId('equipment'),workspaceId,model:'HVAC package',serial:createId('serial'),clientId:deal.clientId,locationId:'o1',status:'quoted'}; repositories.equipment.create(eq); const visit:Visit={id:createId('visit'),workspaceId,title:`Install ${deal.title}`,type:'installation',status:'planned',startsAt:nowIso(),endsAt:nowIso(),district:'Kyiv',priority:'medium',skills:['installation'],relatedEntityType:'deal',relatedEntityId:dealId}; repositories.visits.create(visit); const ins:Installation={id:createId('installation'),workspaceId,equipmentId:eq.id,visitId:visit.id,status:'scheduled'}; repositories.installations.create(ins); record(workspaceId,actor,'installation.create','installation',ins.id,undefined,ins); return {entity:ins,event:emit(workspaceId,actor,'installation_scheduled','installation',ins.id,{dealId})};} completeInstallation(workspaceId:string, actor:User, id:ID){const before={...repositories.installations.get(id)}; const ins=repositories.installations.update(id,{status:'completed',completedAt:nowIso()}); if(!ins) throw new Error('Installation not found'); repositories.visits.update(ins.visitId,{status:'completed'}); record(workspaceId,actor,'installation.complete','installation',id,before,ins); this.activateWarranty(workspaceId,actor,ins.equipmentId); return {entity:ins,event:emit(workspaceId,actor,'installation_completed','installation',id,{equipmentId:ins.equipmentId})};} createServiceRequest(){return undefined;} activateWarranty(workspaceId:string, actor:User, equipmentId:ID){const w:Warranty={id:createId('warranty'),workspaceId,equipmentId,startsAt:nowIso().slice(0,10),endsAt:'2029-06-18',status:'active'}; repositories.warranties.create(w); record(workspaceId,actor,'warranty.activate','warranty',w.id,undefined,w); return w;}}
export const services = { leads:new LeadService(), deals:new DealService(), tasks:new TaskService(), invoices:new InvoiceService(), schedule:new ScheduleService(), hvac:new HvacService() };
