import { authProvider, repositories } from './lib/adapters/local';
import { getDashboardAnalytics } from './lib/analytics/service';
import { businessOsMode } from './lib/config';
import type { Permission } from './lib/domain/types';
import { can } from './lib/permissions/rbac';
import { conflictsFor, minutes, scoreTeam } from './lib/schedule/intelligence';

type Page = 'Dashboard'|'Clients'|'Leads'|'Deals'|'Tasks'|'Schedule'|'Offers'|'Invoices'|'HVAC'|'Settings';
const nav: Page[] = ['Dashboard','Clients','Leads','Deals','Tasks','Schedule','Offers','Invoices','HVAC','Settings'];
const money = (n:number) => new Intl.NumberFormat('uk-UA',{style:'currency',currency:'UAH',maximumFractionDigits:0}).format(n);
const userName = (id?:string) => authProvider.listUsers().find(u=>u.id===id)?.name ?? 'Unassigned';
const esc = (v: unknown) => String(v).replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c] ?? c));
function list(title:string, rows:string[]): string { return `<article class="card"><h3>${esc(title)}</h3>${rows.length?rows.map(r=>`<p>${esc(r)}</p>`).join(''):'<p class="muted">No data yet</p>'}</article>`; }
function table(rows:(string|number)[][]): string { return `<table>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</table>`; }
function two(a:string,b:string): string { return `<div class="two">${a}${b}</div>`; }
function dashboard(ws:string): string { const a=getDashboardAnalytics(ws), events=repositories.events.list(ws), visits=repositories.visits.list(ws), inv=repositories.invoices.list(ws).filter(i=>i.status!=='paid'); const metrics={Leads:a.leadsCount,'Active deals':a.activeDeals,'Won deals':a.wonDeals,Revenue:money(a.revenue),'Unpaid invoices':money(a.unpaidInvoices),'Scheduled installs':a.scheduledInstallations,'Service requests':a.serviceRequests}; return `<section><div class="grid metrics">${Object.entries(metrics).map(([k,v])=>`<article class="card"><small>${esc(k)}</small><strong>${esc(v)}</strong></article>`).join('')}</div>${two(list('Recent events',events.map(e=>`${e.title} · ${e.entityType} ${e.entityId}`)),list('Today / upcoming schedule',visits.map(v=>`${v.title} · ${new Date(v.startsAt).toLocaleString()} · ${v.status}`)))}${two(list('Open invoices',inv.map(i=>`${i.id} · ${i.status} · ${money(i.total)}`)),list('Team workload',a.teamWorkload.map(t=>`${t.team}: ${t.count} visits`)))}</section>`; }
function clients(ws:string): string { const events=repositories.events.list(ws); return `<div class="grid">${repositories.clients.list(ws).map(c=>`<article class="card"><h3>${esc(c.name)}</h3><p>${c.type} · ${c.tags.join(', ')}</p><p>${c.contacts.map(x=>`${x.name} ${x.phone}`).join(' · ')}</p><h4>Objects</h4>${c.objects.map(o=>`<p>${esc(o.address)} · ${o.type}</p>`).join('')}<h4>History</h4>${events.slice(0,3).map(e=>`<small>${e.title} · ${e.createdAt}</small>`).join('')}</article>`).join('')}</div>`; }
function leads(ws:string): string { return table(repositories.leads.list(ws).map(l=>[l.name,l.source,l.status,l.priority,userName(l.assignedUserId),'Action: create deal via workflow'])); }
function deals(ws:string): string { const events=repositories.events.list(ws); return `<div class="grid">${repositories.deals.list(ws).map(d=>`<article class="card"><h3>${esc(d.title)}</h3><p>${d.stage} · ${money(d.value)} · ${userName(d.assignedUserId)}</p><p>Offer: ${d.offerId ?? '—'} · Invoice: ${d.invoiceId ?? '—'}</p><h4>Timeline</h4>${events.filter(e=>e.entityId===d.id||e.entityType==='deal').map(e=>`<small>${e.title} · ${e.createdAt}</small>`).join('')}</article>`).join('')}</div>`; }
function tasks(ws:string): string { return table(repositories.tasks.list(ws).map(t=>[t.title,t.status,t.priority,userName(t.assigneeId),new Date(t.dueAt).toLocaleString()])); }
function schedule(ws:string): string { const visits=repositories.visits.list(ws), teams=repositories.teams.list(ws); return `<div class="grid">${visits.map(v=>`<article class="card"><h3>${esc(v.title)}</h3><p>${v.type} · ${v.status} · ${minutes(v)} min · ${v.district}</p><p>${new Date(v.startsAt).toLocaleString()} → ${new Date(v.endsAt).toLocaleString()}</p><p>Conflicts: ${conflictsFor(v,visits).map(c=>c.title).join(', ') || 'none'}</p><p>Suggested team: ${teams.map(t=>`${t.name} score ${scoreTeam(t,v)}`).join(' · ')}</p></article>`).join('')}</div>`; }
function offers(ws:string): string { return `<div class="grid">${repositories.offers.list(ws).map(o=>`<article class="card"><h3>${esc(o.name)}</h3><p>${o.status}</p>${o.items.map(i=>`<p><span class="pill">${i.type}</span> ${esc(i.name)} × ${i.quantity} = ${money(i.quantity*i.unitPrice)}</p>`).join('')}<strong>Total ${money(o.items.reduce((s,i)=>s+i.quantity*i.unitPrice,0))}</strong></article>`).join('')}</div>`; }
function invoices(ws:string): string { return table(repositories.invoices.list(ws).map(i=>[i.id,i.status,money(i.total),i.dueAt,i.dealId ?? '—'])); }
function hvac(ws:string): string { return `<section>${two(list('Equipment',repositories.equipment.list(ws).map(e=>`${e.model} · ${e.serial} · ${e.status}`)),list('Installations',repositories.installations.list(ws).map(i=>`${i.equipmentId} · ${i.status}`)))}${two(list('Service requests',repositories.serviceRequests.list(ws).map(s=>`${s.issue} · ${s.priority} · ${s.status}`)),list('Warranty',repositories.warranties.list(ws).map(w=>`${w.equipmentId} · ${w.status} · until ${w.endsAt}`)))}</section>`; }
function settings(ws:string): string { const u=authProvider.getCurrentUser(); return `<section><div class="card"><h3>Workspace</h3><p>${authProvider.getWorkspace().name}; local mode uses mock auth, repository seed data, console notifications, mock payments, and local event bus.</p><p class="pill">Current user: ${u.name} / ${u.role}</p></div>${two(list('Roles / users',authProvider.listUsers().map(x=>`${x.role}: ${x.name}`)),list('Rules',repositories.rules.list(ws).map(r=>`WHEN ${r.triggerEventType} IF ${JSON.stringify(r.conditions)} THEN ${r.actions.map(a=>a.type).join(', ')}`)))}${list('Workflows',repositories.workflows.list(ws).map(w=>`${w.name}: ${w.steps.map(s=>s.label).join(' → ')}`))}</section>`; }
function content(page:Page, ws:string): string { return ({Dashboard:dashboard,Clients:clients,Leads:leads,Deals:deals,Tasks:tasks,Schedule:schedule,Offers:offers,Invoices:invoices,HVAC:hvac,Settings:settings}[page])(ws); }
function render(page: Page = 'Dashboard') { const ws=authProvider.getWorkspace(), user=authProvider.getCurrentUser(); const visibleNav=nav.filter(n=>!(n==='Invoices'&&!can(user,'view_finance' as Permission))); document.getElementById('root')!.innerHTML = `<aside><h1>Business OS</h1><p>${ws.name} · ${businessOsMode}</p><p class="pill">Role: ${user.role}</p>${visibleNav.map(n=>`<button data-page="${n}" class="${page===n?'active':''}">${n}</button>`).join('')}</aside><main><header><h2>${page}</h2><span>Lead → Sale → Offer → Schedule → Work → Invoice → Service → Warranty</span></header>${content(page, ws.id)}</main>`; document.querySelectorAll('button[data-page]').forEach(b=>b.addEventListener('click',()=>render((b as HTMLElement).dataset.page as Page))); }
render();
