import { authProvider, notificationProvider, repositories } from './lib/adapters/local';
import { executeBusinessAction, type BusinessActionType } from './lib/application/actions';
import { getDashboardAnalytics } from './lib/analytics/service';
import { businessOsMode } from './lib/config';
import type { Permission } from './lib/domain/types';
import { can } from './lib/permissions/rbac';
import { auditService, eventService } from './lib/services/eventAudit';
import { conflictsFor, minutes, scoreTeam } from './lib/schedule/intelligence';

type Page = 'Dashboard'|'Clients'|'Leads'|'Deals'|'Tasks'|'Schedule'|'Offers'|'Invoices'|'HVAC'|'Settings';
const nav: Page[] = ['Dashboard','Clients','Leads','Deals','Tasks','Schedule','Offers','Invoices','HVAC','Settings'];
let currentPage: Page = 'Dashboard';
let flash = 'Ready';
const money = (n:number) => new Intl.NumberFormat('uk-UA',{style:'currency',currency:'UAH',maximumFractionDigits:0}).format(n);
const userName = (id?:string) => authProvider.listUsers().find(u=>u.id===id)?.name ?? 'Unassigned';
const esc = (v: unknown) => String(v).replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c] ?? c));
function actionButton(type: BusinessActionType, id: string, label: string): string { return `<button class="inline" data-action="${type}" data-id="${esc(id)}">${esc(label)}</button>`; }
function list(title:string, rows:string[]): string { return `<article class="card"><h3>${esc(title)}</h3>${rows.length?rows.map(r=>`<p>${r}</p>`).join(''):'<p class="muted">No data yet</p>'}</article>`; }
function table(rows:(string|number)[][]): string { return `<table>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</table>`; }
function two(a:string,b:string): string { return `<div class="two">${a}${b}</div>`; }
function eventRows(ws:string){return eventService.listRecent(ws).map(e=>`${esc(e.title)} · ${esc(e.entityType)} ${esc(e.entityId)} · ${new Date(e.createdAt).toLocaleString()}`)}
function auditRows(ws:string){return auditService.listRecent(ws).map(a=>`${esc(userName(a.actorUserId))} · ${esc(a.action)} · ${esc(a.entityType)} ${esc(a.entityId)} · ${new Date(a.createdAt).toLocaleString()}`)}
function notificationRows(ws:string){return notificationProvider.list(ws).slice(0,8).map(n=>`${n.read?'✓':'●'} ${esc(n.title)} · ${esc(n.body)}`)}
function dashboard(ws:string): string { const a=getDashboardAnalytics(ws), visits=repositories.visits.list(ws), inv=repositories.invoices.list(ws).filter(i=>i.status!=='paid'); const metrics={Leads:a.leadsCount,'Active deals':a.activeDeals,'Won deals':a.wonDeals,Revenue:money(a.revenue),'Unpaid invoices':money(a.unpaidInvoices),'Scheduled installs':a.scheduledInstallations,'Service requests':a.serviceRequests}; return `<section><div class="grid metrics">${Object.entries(metrics).map(([k,v])=>`<article class="card"><small>${esc(k)}</small><strong>${esc(v)}</strong></article>`).join('')}</div>${two(list('Recent events',eventRows(ws)),list('Notifications',notificationRows(ws)))}${two(list('Open invoices',inv.map(i=>`${esc(i.id)} · ${esc(i.status)} · ${money(i.total)}`)),list('Recent audit logs',auditRows(ws)))}${list('Today / upcoming schedule',visits.map(v=>`${esc(v.title)} · ${new Date(v.startsAt).toLocaleString()} · ${esc(v.status)}`))}</section>`; }
function clients(ws:string): string { const events=repositories.events.list(ws); return `<div class="grid">${repositories.clients.list(ws).map(c=>`<article class="card"><h3>${esc(c.name)}</h3><p>${esc(c.type)} · ${esc(c.tags.join(', '))}</p><p>${esc(c.contacts.map(x=>`${x.name} ${x.phone}`).join(' · '))}</p><h4>Objects</h4>${c.objects.map(o=>`<p>${esc(o.address)} · ${esc(o.type)}</p>`).join('')}<h4>History</h4>${events.slice(0,3).map(e=>`<small>${esc(e.title)} · ${esc(e.createdAt)}</small>`).join('')}</article>`).join('')}</div>`; }
function leads(ws:string): string { return table(repositories.leads.list(ws).map(l=>[esc(l.name),esc(l.source),esc(l.status),esc(l.priority),esc(userName(l.assignedUserId)),`${actionButton('lead.qualify',l.id,'Qualify')}${actionButton('lead.createDeal',l.id,'Create deal via workflow')}`])); }
function deals(ws:string): string { return `<div class="grid">${repositories.deals.list(ws).map(d=>`<article class="card"><h3>${esc(d.title)}</h3><p>${esc(d.stage)} · ${money(d.value)} · ${esc(userName(d.assignedUserId))}</p><p>Offer: ${esc(d.offerId ?? '—')} · Invoice: ${esc(d.invoiceId ?? '—')}</p><div>${actionButton('deal.markWon',d.id,'Mark won')}${actionButton('deal.markLost',d.id,'Mark lost')}<button class="inline" data-stub="offer">Send offer</button></div><h4>Timeline</h4>${eventService.listForEntity(ws,'deal',d.id).map(e=>`<small>${esc(e.title)} · ${esc(e.createdAt)}</small>`).join('') || '<small>No deal events yet</small>'}</article>`).join('')}</div>`; }
function tasks(ws:string): string { return table(repositories.tasks.list(ws).map(t=>[esc(t.title),esc(t.status),esc(t.priority),esc(userName(t.assigneeId)),new Date(t.dueAt).toLocaleString(),t.status==='done'?'Done':actionButton('task.complete',t.id,'Complete')])); }
function schedule(ws:string): string { const visits=repositories.visits.list(ws), teams=repositories.teams.list(ws); return `<div class="grid">${visits.map(v=>`<article class="card"><h3>${esc(v.title)}</h3><p>${esc(v.type)} · ${esc(v.status)} · ${minutes(v)} min · ${esc(v.district)}</p><p>${new Date(v.startsAt).toLocaleString()} → ${new Date(v.endsAt).toLocaleString()}</p><p>Conflicts: ${esc(conflictsFor(v,visits).map(c=>c.title).join(', ') || 'none')}</p><p>Suggested team: ${esc(teams.map(t=>`${t.name} score ${scoreTeam(t,v)}`).join(' · '))}</p>${v.status==='completed'?'':actionButton('visit.complete',v.id,'Complete visit')}</article>`).join('')}</div>`; }
function offers(ws:string): string { return `<div class="grid">${repositories.offers.list(ws).map(o=>`<article class="card"><h3>${esc(o.name)}</h3><p>${esc(o.status)}</p>${o.items.map(i=>`<p><span class="pill">${esc(i.type)}</span> ${esc(i.name)} × ${i.quantity} = ${money(i.quantity*i.unitPrice)}</p>`).join('')}<strong>Total ${money(o.items.reduce((s,i)=>s+i.quantity*i.unitPrice,0))}</strong></article>`).join('')}</div>`; }
function invoices(ws:string): string { return table(repositories.invoices.list(ws).map(i=>[esc(i.id),esc(i.status),money(i.total),esc(i.dueAt),esc(i.dealId ?? '—'),i.status==='paid'?'Paid':actionButton('invoice.markPaid',i.id,'Mark paid')])); }
function hvac(ws:string): string { return `<section>${two(list('Equipment',repositories.equipment.list(ws).map(e=>`${esc(e.model)} · ${esc(e.serial)} · ${esc(e.status)}`)),list('Installations',repositories.installations.list(ws).map(i=>`${esc(i.equipmentId)} · ${esc(i.status)} ${i.status==='completed'?'':actionButton('installation.complete',i.id,'Complete installation')}`)))}${two(list('Service requests',repositories.serviceRequests.list(ws).map(s=>`${esc(s.issue)} · ${esc(s.priority)} · ${esc(s.status)}`)),list('Warranty',repositories.warranties.list(ws).map(w=>`${esc(w.equipmentId)} · ${esc(w.status)} · until ${esc(w.endsAt)}`)))}</section>`; }
function settings(ws:string): string { const u=authProvider.getCurrentUser(); return `<section><div class="card"><h3>Workspace</h3><p>${esc(authProvider.getWorkspace().name)}; local mode uses mock auth, mutable repositories, console notifications, mock payments, and local event bus.</p><p class="pill">Current user: ${esc(u.name)} / ${esc(u.role)}</p></div>${two(list('Roles / users',authProvider.listUsers().map(x=>`${esc(x.role)}: ${esc(x.name)}`)),list('Rules',repositories.rules.list(ws).map(r=>`WHEN ${esc(r.triggerEventType)} IF ${esc(JSON.stringify(r.conditions))} THEN ${esc(r.actions.map(a=>a.type).join(', '))}`)))}${two(list('Workflows',repositories.workflows.list(ws).map(w=>`${esc(w.name)}: ${esc(w.steps.map(s=>s.label).join(' → '))}`)),list('Recent audit logs',auditRows(ws)))}${list('Notifications',notificationRows(ws))}</section>`; }
function content(page:Page, ws:string): string { return ({Dashboard:dashboard,Clients:clients,Leads:leads,Deals:deals,Tasks:tasks,Schedule:schedule,Offers:offers,Invoices:invoices,HVAC:hvac,Settings:settings}[page])(ws); }
function handleAction(type: BusinessActionType, id: string) { const ws=authProvider.getWorkspace().id; const result=executeBusinessAction({workspaceId:ws,type,payload:{id}}); flash = `${result.ok ? '✅' : '❌'} ${result.message}${result.sideEffects?.length ? ` · ${result.sideEffects.join(' · ')}` : ''}`; render(currentPage); }
function render(page: Page = currentPage) { currentPage=page; const ws=authProvider.getWorkspace(), user=authProvider.getCurrentUser(); const visibleNav=nav.filter(n=>!(n==='Invoices'&&!can(user,'view_finance' as Permission))); document.getElementById('root')!.innerHTML = `<aside><h1>Business OS</h1><p>${esc(ws.name)} · ${esc(businessOsMode)}</p><p class="pill">Role: ${esc(user.role)}</p>${visibleNav.map(n=>`<button data-page="${n}" class="${page===n?'active':''}">${n}</button>`).join('')}</aside><main><header><div><h2>${page}</h2><span>Lead → Sale → Offer → Schedule → Work → Invoice → Service → Warranty</span></div><div class="notice">${esc(flash)}</div></header>${content(page, ws.id)}</main>`; document.querySelectorAll('button[data-page]').forEach(b=>b.addEventListener('click',()=>render((b as HTMLElement).dataset.page as Page))); document.querySelectorAll('button[data-action]').forEach(b=>b.addEventListener('click',()=>handleAction((b as HTMLElement).dataset.action as BusinessActionType, (b as HTMLElement).dataset.id ?? ''))); document.querySelectorAll('button[data-stub]').forEach(b=>b.addEventListener('click',()=>{flash='✅ Local offer action stub recorded for production provider replacement'; render(currentPage);})); }
render();
